# Zufällige Arrays mit NumPy

Dieses Notebook demonstriert die Erstellung und Verwendung von zufälligen Arrays mit NumPy.

## Import der benötigten Bibliotheken

Wir importieren NumPy für die Arbeit mit Arrays und zufälligen Zahlen.

In [1]:
import numpy as np

## Setzen des Seeds für den Zufallszahlengenerator

Um reproduzierbare Ergebnisse zu erhalten, setzen wir einen festen Seed-Wert.

In [2]:
# Seed für Reproduzierbarkeit setzen
np.random.seed(42)

## Erstellen von zufälligen Arrays

Wir erstellen verschiedene Arten von zufälligen Arrays mit unterschiedlichen Dimensionen.

In [3]:
# 1D Array mit 10 zufälligen Zahlen zwischen 0 und 1
array_1d = np.random.rand(10)
print("1D Array:")
print(array_1d)

# 2D Array (Matrix) mit 3x4 zufälligen Zahlen
array_2d = np.random.rand(3, 4)
print("\n2D Array:")
print(array_2d)

# 3D Array mit 2x3x2 zufälligen Zahlen
array_3d = np.random.rand(2, 3, 2)
print("\n3D Array:")
print(array_3d)

1D Array:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]

2D Array:
[[0.02058449 0.96990985 0.83244264 0.21233911]
 [0.18182497 0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289 0.13949386]]

3D Array:
[[[0.29214465 0.36636184]
  [0.45606998 0.78517596]
  [0.19967378 0.51423444]]

 [[0.59241457 0.04645041]
  [0.60754485 0.17052412]
  [0.06505159 0.94888554]]]


## Generieren von zufälligen Ganzzahlen

Demonstration der Verwendung von randint() für die Generierung zufälliger Ganzzahlen.

In [4]:
# Zufällige Ganzzahlen zwischen 1 und 100 (10 Zahlen)
random_integers = np.random.randint(1, 101, size=10)
print("Zufällige Ganzzahlen:")
print(random_integers)

# 2D Array mit zufälligen Ganzzahlen
random_integers_2d = np.random.randint(1, 101, size=(4, 4))
print("\nZufällige Ganzzahlen (2D):")
print(random_integers_2d)

Zufällige Ganzzahlen:
[60 14  9 90 53  2 84 92 60 71]

Zufällige Ganzzahlen (2D):
[[44  8 47 35]
 [78 81 36 50]
 [ 4  2  6 54]
 [ 4 54 93 63]]


### Zusammenfassung
In diesem Notebook haben wir gelernt:
- Wie man NumPy für Zufallszahlen verwendet
- Wie man den Seed für Reproduzierbarkeit setzt
- Wie man verschiedene Arten von zufälligen Arrays erstellt
- Wie man zufällige Ganzzahlen generiert